import { Title } from "@mui/icons-material"
import Head from "next/head"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <Title>
          ToDo List
        </Title>
        <meta property="og:title" content="My page title" key="title" />
      </Head>
      <body>{children}</body>
    </html>
  )
}
